from flask import Flask, render_template, request, jsonify, session, g, redirect, url_for
from datetime import timedelta
from cryptography.fernet import InvalidToken
import hmac
import secrets
import uuid
import sqlite3
import os
import json

from security.encryption import encrypt_text, decrypt_text
from nlp_model import analyze_text
from risk_engine import determine_risk
from database.init_db import initialize_database
from security.session_key import get_session_key

app = Flask(__name__)
app.config.update(
    MAX_CONTENT_LENGTH=128 * 1024,
    SECRET_KEY=get_session_key(),
    SESSION_COOKIE_HTTPONLY=True,
    SESSION_COOKIE_SAMESITE='Lax',
    SESSION_COOKIE_SECURE=os.environ.get('SPROUT_COOKIE_SECURE') == '1',
    PERMANENT_SESSION_LIFETIME=timedelta(hours=8),
)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# The public prototype only opens the demo database. Existing real records are preserved.
DB_PATH = os.environ.get('SPROUT_DEMO_DB_PATH', os.path.join(BASE_DIR, 'database', 'demo.db'))
if os.path.realpath(DB_PATH) == os.path.realpath(os.path.join(BASE_DIR, 'database', 'sprout.db')):
    raise ValueError('The demo must use its own database, separate from existing records.')
MOODS = {'great', 'good', 'okay', 'low', 'difficult'}
ALERT_STATUSES = {'PENDING', 'REVIEWED', 'RESOLVED'}
initialize_database(DB_PATH)


def get_db_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute('PRAGMA foreign_keys = ON')
    return conn


def remove_legacy_samples():
    """Remove only the exact demonstration records previously generated by Sprout."""
    conn = get_db_connection()
    try:
        with conn:
            conn.execute(
                "DELETE FROM escalation_alerts WHERE student_id LIKE 'GUEST-%' AND signal_summary = ?",
                ('Sample alert for demonstrating the counselor review workflow.',)
            )
            entries = conn.execute(
                "SELECT entry_id, encrypted_content FROM journal_entries WHERE student_id LIKE 'GUEST-%'"
            ).fetchall()
            for entry in entries:
                try:
                    content = decrypt_text(entry['encrypted_content'])
                except (InvalidToken, ValueError, UnicodeDecodeError):
                    continue
                if content == 'Sample reflection: I made time to check in with myself today.':
                    conn.execute('DELETE FROM journal_entries WHERE entry_id = ?', (entry['entry_id'],))
    finally:
        conn.close()


remove_legacy_samples()


def csrf_token():
    if 'csrf_token' not in session:
        session['csrf_token'] = secrets.token_urlsafe(32)
    return session['csrf_token']


@app.context_processor
def template_helpers():
    return {'csrf_token': csrf_token, 'demo_student_id': g.student_id}


def create_demo_workspace():
    student_id = 'GUEST-' + uuid.uuid4().hex
    conn = get_db_connection()
    try:
        with conn:
            stale = "SELECT student_id FROM students WHERE student_id LIKE 'GUEST-%' AND created_at < datetime('now', '-1 day')"
            for table in ['journal_entries', 'escalation_alerts', 'daily_stats']:
                conn.execute(f'DELETE FROM {table} WHERE student_id IN ({stale})')
            conn.execute(f'DELETE FROM students WHERE student_id IN ({stale})')
            conn.execute('INSERT INTO students (student_id, name) VALUES (?, ?)', (student_id, 'Guest'))
    finally:
        conn.close()
    session.clear()
    session['demo_student_id'] = student_id
    session.permanent = True
    return student_id


@app.before_request
def prepare_demo_workspace():
    g.student_id = None
    if request.endpoint not in {
        'student_home', 'counselor_dashboard', 'save_journal', 'get_student_history',
        'get_counselor_alerts', 'update_alert_status', 'reset_demo',
    }:
        return

    # A signed browser cookie identifies the demo workspace. There are no accounts.
    student_id = session.get('demo_student_id') or session.get('guest_student_id')
    conn = get_db_connection()
    try:
        student = conn.execute(
            "SELECT student_id FROM students WHERE student_id = ? "
            "AND student_id LIKE 'GUEST-%' AND created_at >= datetime('now', '-1 day')",
            (student_id,)
        ).fetchone() if student_id else None
    finally:
        conn.close()
    if student:
        g.student_id = student['student_id']
        session['demo_student_id'] = g.student_id
        for old_key in ['guest_student_id', 'guest_role', 'user_id']:
            session.pop(old_key, None)
    elif request.endpoint in {'student_home', 'counselor_dashboard'} and request.method in {'GET', 'HEAD'}:
        g.student_id = create_demo_workspace()
    else:
        return jsonify(error='Your demo workspace expired. Copy any draft, then refresh Sprout.'), 409

    if request.method in {'POST', 'PATCH', 'PUT', 'DELETE'}:
        supplied = request.headers.get('X-CSRF-Token') or request.form.get('csrf_token', '')
        expected = session.get('csrf_token', '')
        if not expected or not hmac.compare_digest(expected.encode(), supplied.encode()):
            return jsonify(error='Refresh the page and try again.'), 400


@app.after_request
def protect_private_responses(response):
    if request.endpoint != 'static':
        response.headers['Cache-Control'] = 'no-store'
    response.headers['X-Content-Type-Options'] = 'nosniff'
    response.headers['X-Frame-Options'] = 'SAMEORIGIN'
    return response


@app.route('/')
def student_home():
    return render_template('index.html')


@app.route('/counselor')
def counselor_dashboard():
    return render_template('counselor.html')


@app.route('/login')
def old_login_link():
    # Old shared links still open the prototype; no sign-in page remains.
    return redirect(url_for('student_home'))


@app.route('/demo/reset', methods=['POST'])
def reset_demo():
    create_demo_workspace()
    return redirect(url_for('student_home'))


def read_json_object():
    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        raise ValueError('Send a JSON object.')
    return data


def read_chip_list(data, field):
    values = data.get(field, [])
    if not isinstance(values, list) or len(values) > 16:
        raise ValueError(f'{field} must be a list of up to 16 selections.')
    if any(not isinstance(value, str) or not value.strip() or len(value) > 100 for value in values):
        raise ValueError(f'{field} contains an invalid selection.')
    return list(dict.fromkeys(value.strip() for value in values))


def decode_chip_list(value):
    try:
        values = json.loads(value) if value else []
        return [item for item in values if isinstance(item, str)] if isinstance(values, list) else []
    except (json.JSONDecodeError, TypeError):
        return []


def utc_timestamp(value):
    # SQLite CURRENT_TIMESTAMP is UTC; make the timezone explicit in the API.
    return value.replace(' ', 'T') + 'Z' if value else None


@app.errorhandler(413)
def request_too_large(error):
    return jsonify(error='This reflection is too large. Please shorten it.'), 413


@app.route('/api/journal', methods=['POST'])
def save_journal():
    try:
        data = read_json_object()
        student_id = g.student_id
        content = data.get('content', '')
        mood = data.get('mood', '')
        if not isinstance(student_id, str) or not student_id.strip() or len(student_id) > 100:
            raise ValueError('Invalid student identifier.')
        if not isinstance(content, str) or not content.strip():
            raise ValueError('Journal content cannot be empty.')
        content = content.strip()
        if len(content) > 20000:
            raise ValueError('Keep reflections to 20,000 characters or fewer.')
        if not isinstance(mood, str) or mood not in MOODS:
            raise ValueError('Choose a valid mood.')
        day_factors = read_chip_list(data, 'day_factors')
        helpful_needs = read_chip_list(data, 'helpful_needs')
    except ValueError as error:
        return jsonify(error=str(error)), 400

    conn = get_db_connection()
    try:
        if not conn.execute('SELECT 1 FROM students WHERE student_id = ?', (student_id,)).fetchone():
            return jsonify(error='Student not found.'), 400

        # Analyze before writing, so a failed model never leaves a half-saved entry.
        analysis = analyze_text(content)
        risk = determine_risk(analysis['prediction'], analysis['confidence'])
        with conn:
            conn.execute(
                'INSERT INTO journal_entries '
                '(student_id, encrypted_content, mood, day_factors, helpful_needs) '
                'VALUES (?, ?, ?, ?, ?)',
                (student_id, encrypt_text(content), mood,
                 json.dumps(day_factors, ensure_ascii=False),
                 json.dumps(helpful_needs, ensure_ascii=False))
            )
            if risk['risk_level'] in ['ELEVATED', 'HIGH']:
                conn.execute(
                    'INSERT INTO escalation_alerts (student_id, risk_level, signal_summary) '
                    'VALUES (?, ?, ?)',
                    (student_id, risk['risk_level'], risk['signal_summary'])
                )
    except Exception:
        app.logger.error('Could not save a reflection; transaction rolled back.')
        return jsonify(error='Could not save your reflection. Please try again.'), 503
    finally:
        conn.close()

    return jsonify(
        status='success', message='Journal securely saved.',
        prediction=analysis['prediction'], confidence=analysis['confidence'],
        risk_level=risk['risk_level']
    )


@app.route('/api/student/history', methods=['GET'])
def get_student_history():
    # The browser workspace determines ownership, never a submitted student ID.
    student_id = g.student_id
    conn = get_db_connection()
    try:
        entries = conn.execute(
            'SELECT entry_id, student_id, encrypted_content, mood, day_factors, '
            'helpful_needs, created_at FROM journal_entries WHERE student_id = ? '
            'ORDER BY created_at DESC, entry_id DESC', (student_id,)
        ).fetchall()
    finally:
        conn.close()

    return jsonify([
        {
            'entry_id': entry['entry_id'], 'student_id': entry['student_id'],
            'content': decrypt_text(entry['encrypted_content']), 'mood': entry['mood'],
            'day_factors': decode_chip_list(entry['day_factors']),
            'helpful_needs': decode_chip_list(entry['helpful_needs']),
            'created_at': utc_timestamp(entry['created_at']),
        }
        for entry in entries
    ])


@app.route('/api/counselor/alerts', methods=['GET'])
def get_counselor_alerts():
    conn = get_db_connection()
    try:
        query = (
            'SELECT alert_id, student_id, risk_level, signal_summary, status, '
            'created_at, reviewed_at, resolved_at FROM escalation_alerts '
        )
        query += 'WHERE student_id = ? '
        parameters = (g.student_id,)
        alerts = conn.execute(query + 'ORDER BY created_at DESC, alert_id DESC', parameters).fetchall()
    finally:
        conn.close()
    result = []
    for alert in alerts:
        item = dict(alert)
        for field in ['created_at', 'reviewed_at', 'resolved_at']:
            item[field] = utc_timestamp(item[field])
        result.append(item)
    return jsonify(result)


@app.route('/api/counselor/alerts/<int:alert_id>', methods=['PATCH'])
def update_alert_status(alert_id):
    try:
        data = read_json_object()
        status = data.get('status')
        if not isinstance(status, str) or status not in ALERT_STATUSES:
            raise ValueError('Choose PENDING, REVIEWED, or RESOLVED.')
    except ValueError as error:
        return jsonify(error=str(error)), 400

    conn = get_db_connection()
    try:
        with conn:
            parameters = (status, status, status, alert_id, g.student_id)
            cursor = conn.execute(
                'UPDATE escalation_alerts SET status = ?, '
                'reviewed_at = CASE WHEN ? IN (\'REVIEWED\', \'RESOLVED\') '
                'THEN COALESCE(reviewed_at, CURRENT_TIMESTAMP) ELSE reviewed_at END, '
                'resolved_at = CASE WHEN ? = \'RESOLVED\' '
                'THEN COALESCE(resolved_at, CURRENT_TIMESTAMP) ELSE NULL END '
                'WHERE alert_id = ? AND student_id = ?', parameters
            )
            if cursor.rowcount == 0:
                return jsonify(error='Alert not found.'), 404
    finally:
        conn.close()
    return jsonify(status='success', alert_id=alert_id, alert_status=status)


if __name__ == '__main__':
    app.run(debug=os.environ.get('SPROUT_DEBUG') == '1', port=5001)
